[package]
name = "tic-tac-toe2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
winapi = { version = "0.3.9", features = ["consoleapi", "processenv","winbase","handleapi"]}
