[package]
name = "tic-tac-toe2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_System_Console"
]
